### ISSUE TITLE
Feature Appointment Service

### ISSUE THREAD

**Issue by wall030** [GoldJns/camunda-nextgen#74]
The Appointment Service will manage the scheduling, updating, and cancellation of appointments in the system.

Goals:
- Create Appointment: Implement the ability to schedule new appointments with doctor.
- Edit Appointment: Provide functionality to update existing appointments.
- Delete Appointment: Implement the ability to cancel appointments from the system.

Tasks:
- Create Appointment
- Edit Appointment
- Delete Appointment

**Comment by Zohaib770** [comment]
5d8dd33 - worker & bpmn diagram for edit/delete

**Comment by Zohaib770** [comment]
66c466d - ceateAppoinment bpmn fertig

**Comment by Zohaib770** [comment]
29dd60a - add worker
